apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: jhowrf/goapp:latest
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"

        # startup probe
#        startupProbe:
#          httpGet:
#            path: /
#            port: 8080
#          failureThreshold: 10
#          periodSeconds: 10

         # readiness probe
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 8080
#          failureThreshold: 2
#          periodSeconds: 10
#          timeoutSeconds: 5

        # liveness probe
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8080
#          failureThreshold: 5
#          periodSeconds: 10
#          timeoutSeconds: 5
#          successThreshold: 1

        ports:
        - containerPort: 8080